# Generated by Django 5.1.6 on 2025-04-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="can_join",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="name",
            field=models.CharField(default="World of Destruction", max_length=100),
        ),
    ]
