# Generated by Django 5.1.6 on 2025-04-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_game_can_join_game_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tools",
            name="population_growth_rate",
            field=models.FloatField(default=10.0),
        ),
    ]
